### ISSUE TITLE
Webapp hosting method

### ISSUE THREAD

**Issue by bee-wah** [DanTarl/buzz-controller-web-app#1]
How did you set this up so that your friends could access the site over the Internet? I assume you have to be running the web app on your local machine so that it can interact with the PCSX2 plugin, so do you need to forward requests to your own computer? Any suggestions on how to do that? I have the web app running locally but I'm not very familiar with the networking components.

**Comment by bee-wah** [comment]
Or did you just set up port forwarding?

**Comment by DanTarl** [comment]
I just use port forwarding from my router to the machine hosting the server and PCSX2. I also use a free public hostname so it's easier to share (also easier to generate a certificate if you're using SSL).

**Comment by bee-wah** [comment]
Thanks! I got it working with port forwarding. I still need to figure out how to get https configured but I just played a Buzz game with my friends over Discord and it worked like a charm.
